name: Sentinel Ingestion Pipeline

on:
  workflow_dispatch:
    inputs:
      product_id:
        description: 'Product ID'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install gdal
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ppa && apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          pip install setuptools==57.5.0
          pip install GDAL==$(gdal-config --version)
          
      - name: execute py script
        env:
          apiusr: ${{ secrets.APIUSR }}
          apipass: ${{ secrets.APIPASS }}
          acc_key: ${{ secrets.ACC_KEY }}
          sec_key: ${{ secrets.SEC_KEY }}
          bucket: ${{ secrets.BUCKET }}
          endpoint_url: ${{ secrets.ENDPOINT_URL }}
        run: python3 sen_pip.py --product_id ${{ inputs.product_id }}